// lib/report-actions.ts
// Report saving - uses Supabase storage

'use server';

import { getServerSession } from 'next-auth';
import { authOptions } from '@proselenosebooks/auth-core/lib/auth';
import { uploadFileToProject } from '@/lib/supabase-project-actions';

type ActionResult<T = any> = {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
};

interface ExtendedSession {
  user: {
    id: string;
    email?: string;
    name?: string;
    image?: string;
  };
  accessToken?: string;
}

export async function saveToolReportAction(
  toolId: string,
  toolResult: string,
  _projectFolderId: string,
  currentProvider: string,
  currentModel: string,
  manuscriptFileName: string,
  currentProject: string
): Promise<ActionResult> {
  try {
    const session = await getServerSession(authOptions) as ExtendedSession;
    if (!session || !session.user?.id) {
      return { success: false, error: 'Not authenticated' };
    }

    const userId = session.user.id;

    if (!toolResult || !currentProject) {
      return { success: false, error: 'Tool result and project name are required' };
    }

    // Create human-readable timestamp
    const formatter = new Intl.DateTimeFormat('en-US', {
      weekday: 'long',
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true
    });
    const dateTimeStr = formatter.format(new Date());
    
    // Create filename timestamp (safe for filenames)
    const timestamp = new Date().toISOString().replace(/[-:.]/g, '').substring(0, 15);
    
    // Extract tool name from toolId (e.g., "Core Editing Tools/copy_editing.txt" -> "copy_editing")
    const toolName = toolId.split('/').pop()?.replace('.txt', '') || 'tool_report';
    const cleanToolName = toolName.toLowerCase()
      .replace(/[^a-z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');
    
    const baseFilename = `${cleanToolName}_${timestamp}`;
    const reportFilename = `${baseFilename}.txt`;
    
    // Get display name for the tool
    const displayToolName = toolName
      .split('_')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
    
    // Create full manuscript path
    const manuscriptPath = `${currentProject} › ${manuscriptFileName}`;
    
    // format the Report content
    const reportWithStats = `
${displayToolName.toUpperCase()} REPORT

Date: ${dateTimeStr}

Model: ${currentProvider}:${currentModel}

Manuscript File: ${manuscriptPath}

${toolResult}

---
Report generated by Proselenos
https://proselenos.com
`;

    // Save the report to Supabase storage
    await uploadFileToProject(userId, currentProject, reportFilename, reportWithStats);
    const reportPath = `${currentProject}/${reportFilename}`;

    return {
      success: true,
      data: {
        fileName: reportFilename,
        displayName: displayToolName,
        timestamp: dateTimeStr,
        projectPath: reportPath,
        fileId: reportPath
      },
      message: `Report saved: ${reportFilename}`
    };
  } catch (error: any) {
    console.error('Error saving tool report:', error);
    return {
      success: false,
      error: error.message || 'Failed to save report'
    };
  }
}