// app/ai-tools/AIToolsSection.tsx

'use client';

import { useState, useEffect } from 'react';
import { ThemeConfig } from '../shared/theme';
import StyledSmallButton from '@/components/StyledSmallButton';
import { showAlert } from '../shared/alerts';
import ToolProgressIndicator from './ToolProgressIndicator';
import DualPanelEditor from './DualPanelEditor';
import WritingAssistantModal from '../writing-assistant/WritingAssistantModal';
import OneByOneModal from '../one-by-one/OneByOneModal';
import { getToolPrompt, saveManuscript } from '@/services/manuscriptStorage';
import ChatButton from '@/components/ChatButton';
import { isValidToolReport } from '@/utils/parseToolReport';
// createOrUpdateFileAction removed - saves go to IndexedDB now

interface AIToolsSectionProps {
  // Session
  session: any;

  // Tool selection
  selectedCategory: string;
  selectedTool: string;
  toolsInCategory: any[];
  toolsReady: boolean;
  isInstallingToolPrompts: boolean;

  // Execution state
  toolExecuting: boolean;
  toolResult: string;
  toolJustFinished: boolean;
  savedReportFileName: string | null;
  savedReportFileId: string | null;

  // Timer
  elapsedTime: number;

  // Cached manuscript content
  manuscriptContent: string;

  // Project state (kept for compatibility)
  currentProject: string | null;
  currentProjectId: string | null;
  isStorageOperationPending: boolean;
  isSystemInitializing: boolean;

  // Theme
  theme: ThemeConfig;
  isDarkMode: boolean;

  // AI model info for report formatting
  currentProvider?: string;
  currentModel?: string;
  hasConfiguredProvider?: boolean;
  hasApiKey?: boolean;

  // Callbacks
  onCategoryChange: (category: string) => void;
  onToolChange: (tool: string) => void;
  onClearTool: () => void;
  onExecuteTool: () => void;
  onLoadFileIntoEditor?: (content: string, fileName: string, fileId?: string) => void;
  onModelsClick: () => void;
  onSettingsClick: () => void;
}

export default function AIToolsSection({
  session: _session,
  selectedCategory,
  selectedTool,
  toolsInCategory,
  toolsReady,
  isInstallingToolPrompts,
  toolExecuting,
  toolResult,
  toolJustFinished,
  savedReportFileName,
  savedReportFileId,
  elapsedTime,
  manuscriptContent,
  currentProject,
  currentProjectId,
  isStorageOperationPending,
  isSystemInitializing,
  theme,
  isDarkMode,
  currentProvider = 'unknown',
  currentModel = 'unknown',
  hasConfiguredProvider: _hasConfiguredProvider = false,
  hasApiKey = false,
  onCategoryChange,
  onToolChange,
  onClearTool,
  onExecuteTool,
  onLoadFileIntoEditor,
  onModelsClick,
  onSettingsClick,
}: AIToolsSectionProps) {
  
  // Dual panel editor state
  const [showDualEditor, setShowDualEditor] = useState(false);
  const [editorManuscriptContent, setEditorManuscriptContent] = useState('');

  // AI Writing Assistant state
  const [showWritingAssistant, setShowWritingAssistant] = useState(false);

  // One-by-one editing state
  const [showOneByOne, setShowOneByOne] = useState(false);
  
  // Tool prompt editing state
  const [isLoadingPrompt, setIsLoadingPrompt] = useState(false);

  // Preload markdown editor when tool completes
  useEffect(() => {
    if (toolJustFinished) {
      // Warm up the markdown editor bundle in the background
      import('@uiw/react-md-editor');
    }
  }, [toolJustFinished]);

  // Handler for close/reopen modal functionality
  const handleWritingAssistantCloseReopen = () => {
    // Close the modal first
    setShowWritingAssistant(false);
    
    // Reopen immediately after a brief delay
    setTimeout(() => {
      setShowWritingAssistant(true);
    }, 150); // 150ms delay for smooth UX
  };

  const formatFullReport = (
    toolResult: string,
    toolId: string,
    currentProvider: string,
    currentModel: string,
    manuscriptFileName: string,
    currentProject: string
  ) => {
    // Create human-readable timestamp like the original Node.js app
    const formatter = new Intl.DateTimeFormat('en-US', {
      weekday: 'long',
      month: 'long',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
    const dateTimeStr = formatter.format(new Date());
    
    // Extract tool name from toolId (e.g., "Core Editing Tools/copy_editing.txt" -> "copy_editing")
    const toolName = toolId.split('/').pop()?.replace('.txt', '') || 'tool_report';
    
    // Get display name for the tool
    const displayToolName = toolName
      .split('_')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
    
    // Create full manuscript path
    const manuscriptPath = `${currentProject} › ${manuscriptFileName}`;
    
    // Format the report content exactly like the original Node.js app with manuscript file info
    return `
${displayToolName.toUpperCase()} REPORT

Date: ${dateTimeStr}

Model: ${currentProvider}:${currentModel}
      
Manuscript File: ${manuscriptPath}

${toolResult}

---
Report generated by Proselenos
https://proselenos.com
`;
  };

  const handleEditClick = () => {
    if (!manuscriptContent) return;
    setEditorManuscriptContent(manuscriptContent);
    setShowDualEditor(true);
  };

  // One-by-one editing handlers
  const handleOneByOneClick = () => {
    if (!manuscriptContent) return;
    setShowOneByOne(true);
  };

  const handleOneByOneSave = async (content: string) => {
    // Save the updated manuscript to IndexedDB
    await saveManuscript(content);
  };

  const handleCategoryChange = (category: string) => {
    onCategoryChange(category);
    onToolChange(''); // Reset tool selection when category changes
  };

  const handleToolChange = (tool: string) => {
    onToolChange(tool);
  };

  const handlePromptEdit = async () => {
    if (!selectedTool || !onLoadFileIntoEditor || isLoadingPrompt) return;

    setIsLoadingPrompt(true);
    try {
      const content = await getToolPrompt(selectedTool);
      if (content) {
        // Pass with prompt: prefix so Editor knows to use prompt mode
        onLoadFileIntoEditor(content, `prompt:${selectedTool}`, selectedTool);
      } else {
        showAlert('Failed to load tool prompt', 'error', undefined, isDarkMode);
      }
    } catch (error) {
      showAlert('Error loading tool prompt', 'error', undefined, isDarkMode);
    } finally {
      setIsLoadingPrompt(false);
    }
  };

  return (
    <div
      style={{
        position: 'relative',
        marginBottom: '12px',
        backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)',
        border: `2px solid ${isDarkMode ? 'rgba(120, 180, 120, 0.6)' : 'rgba(80, 140, 80, 0.5)'}`,
        borderRadius: '8px',
        padding: '12px',
      }}
    >
      {/* Title positioned on border */}
      <h2 style={{
        position: 'absolute',
        top: '-10px',
        left: '12px',
        fontSize: '16px',
        fontWeight: 'bold',
        fontStyle: 'italic',
        color: theme.text,
        backgroundColor: theme.bg,
        paddingLeft: '6px',
        paddingRight: '6px',
        margin: 0
      }}>
        AI tools:
      </h2>

      {/* Provider:Model display line */}
      <div style={{
        fontSize: '10px',
        color: (hasApiKey && currentModel) ? '#4285F4' : '#dc3545',
        fontFamily: 'monospace',
        marginBottom: '12px',
        marginTop: '8px'
      }}>
        {!hasApiKey ? (
          <span>No AI API key</span>
        ) : !currentModel ? (
          <span>Your Key is valid, now click Models</span>
        ) : (
          <span title={`Provider: ${currentProvider}, Model: ${currentModel}`}>
            {currentProvider}:{currentModel}
          </span>
        )}
      </div>

      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          marginBottom: '6px',
        }}
      >
        {/* Left group: AI settings buttons */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          {/* AI settings and Chat buttons group */}
          <div style={{
            display: 'flex',
            gap: '4px',
            padding: '3px 6px',
            border: `1px solid ${isDarkMode ? '#888' : '#666'}`,
            borderRadius: '4px',
            backgroundColor: isDarkMode ? 'rgba(136, 136, 136, 0.1)' : 'rgba(102, 102, 102, 0.08)'
          }}>
            <span style={{ fontSize: '9px', color: theme.textSecondary, marginRight: '2px', alignSelf: 'center' }}> </span>
            <StyledSmallButton
              onClick={onModelsClick}
              disabled={isSystemInitializing || toolExecuting}
              theme={theme}
              styleOverrides={{ fontSize: '10px', padding: '2px 8px', height: '20px', lineHeight: 1 }}
            >
              Models
            </StyledSmallButton>
            <StyledSmallButton
              onClick={onSettingsClick}
              disabled={isSystemInitializing || isStorageOperationPending || toolExecuting}
              theme={theme}
              styleOverrides={{ fontSize: '10px', padding: '2px 8px', height: '20px', lineHeight: 1 }}
            >
              Key
            </StyledSmallButton>
            <ChatButton
              isDarkMode={isDarkMode}
              isSystemInitializing={isSystemInitializing}
              hasApiKey={hasApiKey}
              toolExecuting={toolExecuting}
              styleOverrides={{ fontSize: '10px', padding: '2px 8px', height: '20px', lineHeight: 1 }}
            />
            <StyledSmallButton
              onClick={() => setShowWritingAssistant(true)}
              disabled={isSystemInitializing || isStorageOperationPending || toolExecuting || !hasApiKey}
              theme={theme}
              styleOverrides={{ fontSize: '10px', padding: '2px 8px', height: '20px', lineHeight: 1 }}
            >
              Writing Assistant
            </StyledSmallButton>
          </div>
        </div>
      </div>

      {/* Divider line */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        margin: '8px 0',
        color: theme.textMuted
      }}>
        <div style={{ width: '80px', height: '1px', backgroundColor: isDarkMode ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.15)' }} />
        <span style={{ padding: '0 12px', fontSize: '11px', fontStyle: 'italic' }}>or</span>
        <div style={{ flex: 1, height: '1px', backgroundColor: isDarkMode ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.15)' }} />
      </div>

      <select
        value={selectedCategory}
        onChange={(e) => handleCategoryChange(e.target.value)}
        disabled={!toolsReady || toolExecuting || !hasApiKey}
        style={{
          width: '100%',
          maxWidth: '300px',
          padding: '4px 8px',
          backgroundColor: toolsReady && currentProject ? theme.inputBg : '#666',
          color: toolsReady && currentProject ? theme.text : '#999',
          border: `1px solid ${theme.border}`,
          borderRadius: '3px',
          fontSize: '11px',
          marginBottom: '8px',
          cursor: toolsReady && currentProject ? 'pointer' : 'not-allowed',
        }}
      >
        <option value="">
          {toolsReady
            ? 'Select a category...'
            : isInstallingToolPrompts
            ? 'Installing tools...'
            : 'Loading tools...'}
        </option>
        <option value="Core Editing Tools">Core Editing Tools</option>
        <option value="Other Editing Tools">Other Editing Tools</option>
        {/* <option value="AI Writing Tools">AI Writing Tools</option> */}
        <option value="User Tools">User Tools</option>
      </select>

      {/* Tool dropdown - separate row for mobile */}
      <div style={{ marginBottom: '8px' }}>
        <select
          value={selectedTool}
          onChange={(e) => handleToolChange(e.target.value)}
          disabled={!selectedCategory || !toolsReady || toolExecuting || !hasApiKey}
          style={{
            width: '100%',
            maxWidth: '300px',
            padding: '4px 8px',
            backgroundColor:
              selectedCategory && toolsReady && currentProject ? theme.inputBg : '#666',
            color: selectedCategory && toolsReady && currentProject ? theme.text : '#999',
            border: `1px solid ${theme.border}`,
            borderRadius: '3px',
            fontSize: '11px',
            cursor:
              selectedCategory && toolsReady && currentProject ? 'pointer' : 'not-allowed',
          }}
        >
          {/* Placeholder option */}
          <option value="">
            {!toolsReady
              ? isInstallingToolPrompts
                ? 'Installing tools...'
                : 'Loading tools...'
              : selectedCategory
              ? 'Select a tool...'
              : 'Please select a category first'}
          </option>

          {/* Sorted tool options */}
          {[...toolsInCategory]
            .sort((a, b) => {
              const nameA = a.name.replace(/_/g, ' ').toLowerCase();
              const nameB = b.name.replace(/_/g, ' ').toLowerCase();
              return nameA.localeCompare(nameB);
            })
            .map((tool) => (
              <option key={tool.id} value={tool.id}>
                {tool.name
                  .split('_')
                  .map((word: string) => word.charAt(0).toUpperCase() + word.slice(1))
                  .join(' ')}
              </option>
            ))}
        </select>
      </div>

      {/* Tool action buttons - separate row beneath dropdown for mobile */}
      <div
        style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '8px', marginBottom: '8px' }}
      >
        <StyledSmallButton
          onClick={handlePromptEdit}
          disabled={
            isSystemInitializing ||
            !selectedTool ||
            !toolsReady ||
            toolExecuting ||
            isLoadingPrompt ||
            !hasApiKey
          }
          theme={theme}
        >
          {isLoadingPrompt ? 'Loading...' : 'Prompt'}
        </StyledSmallButton>

        <StyledSmallButton
          onClick={onClearTool}
          disabled={
            isSystemInitializing ||
            (!toolResult && elapsedTime === 0) ||
            toolExecuting
          }
          theme={theme}
        >
          Clear
        </StyledSmallButton>

        <StyledSmallButton
          onClick={onExecuteTool}
          disabled={
            isSystemInitializing ||
            !selectedTool ||
            toolExecuting ||
            !toolsReady ||
            isStorageOperationPending ||
            toolJustFinished ||
            !hasApiKey
          }
          theme={theme}
        >
          {toolExecuting ? 'Running...' : 'Run'}
        </StyledSmallButton>

        <ToolProgressIndicator
          toolExecuting={toolExecuting}
          elapsedTime={elapsedTime}
          theme={theme}
          toolResult={toolResult}
          onEditClick={handleEditClick}
        />

        {/* One-by-one button - appears when tool finishes with OBO-formatted results */}
        {!toolExecuting && elapsedTime > 0 && toolResult && isValidToolReport(toolResult) && (
          <StyledSmallButton
            onClick={handleOneByOneClick}
            theme={theme}
            styleOverrides={{ fontSize: '10px', padding: '2px 8px', fontWeight: 'bold' }}
          >
            One-by-one
          </StyledSmallButton>
        )}
      </div>
      
      {/* Dual Panel Editor Modal */}
      {showDualEditor && manuscriptContent && (
        <DualPanelEditor
          isVisible={showDualEditor}
          onClose={() => setShowDualEditor(false)}
          manuscriptContent={editorManuscriptContent}
          manuscriptName="manuscript.txt"
          manuscriptFileId="manuscript.txt"
          aiReport={
            selectedTool && currentProject
              ? formatFullReport(
                  toolResult,
                  selectedTool,
                  currentProvider,
                  currentModel,
                  'manuscript.txt',
                  currentProject as string
                )
              : toolResult
          }
          savedReportFileName={savedReportFileName}
          reportFileId={savedReportFileId}
          theme={theme}
          isDarkMode={isDarkMode}
          currentProject={currentProject}
          currentProjectId={currentProjectId}
        />
      )}
      
      {/* AI Writing Assistant Modal */}
      {showWritingAssistant && (
        <WritingAssistantModal
          isOpen={showWritingAssistant}
          onClose={() => setShowWritingAssistant(false)}
          currentProject={currentProject}
          currentProjectId={currentProjectId}
          theme={theme}
          isDarkMode={isDarkMode}
          currentProvider={currentProvider || 'unknown'}
          currentModel={currentModel || 'unknown'}
          session={_session}
          onLoadFileIntoEditor={onLoadFileIntoEditor}
          onModalCloseReopen={handleWritingAssistantCloseReopen}
        />
      )}

      {/* One-by-one Editing Modal */}
      {showOneByOne && manuscriptContent && (
        <OneByOneModal
          isOpen={showOneByOne}
          theme={theme}
          isDarkMode={isDarkMode}
          projectName={currentProject}
          fileName="manuscript.txt"
          filePath="manuscript.txt"
          manuscriptContent={manuscriptContent}
          reportContent={toolResult}
          onClose={() => setShowOneByOne(false)}
          onSave={handleOneByOneSave}
        />
      )}
    </div>
  );
}